### PR TITLE
Basic seed data

### PR DESCRIPTION
**Pull request by iamstevedavis**
Relies on https://github.com/KrisBraun/sanctuary-patient-api/pull/7

Create basic seed data. Run with `npm run seed`. 

Might be worth moving migrations and seeds into a `sql` folder and setting up dockerfile so it correctly moves the new sql directories. We can then update the knexfile.js to look there for migrations and seeds by providing `migrations` and `seeds` configs with the applicable path.

### CODE REVIEW

**Comment by KrisBraun** [comment]
@iamstevedavis Do you want to amend this to allow merging without #7?

**Comment by iamstevedavis** [comment]
> @iamstevedavis Do you want to amend this to allow merging without #7?

Yes.

**Comment by iamstevedavis** [comment]
D: finally got it right... this is good for review.

**Comment by KrisBraun** [comment]
Looks good, good to merge!

**Pull request merged**
